<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>99252e89-57fb-4c7e-9289-d6be9663fd61</groupId>
  <artifactId>mulesoft-api-parent</artifactId>
  <version>1.0.31</version>
  <packaging>pom</packaging>

  <name>MuleSoft API projects</name>

  <modules>
    <module>common-mule-config</module>
    <module>todo-api</module>
  </modules>
  <distributionManagement>
    <repository>
      <id>anypoint-exchange-v3</id>
      <name>Anypoint Exchange</name>
      <url>https://maven.anypoint.mulesoft.com/api/v3/organizations/${project.groupId}/maven</url>
      <layout>default</layout>
    </repository>
  </distributionManagement>
</project>
